volumes:
  mailculator-processor-go-deps:
  mailculator-processor-db:

services:
  develop:
    profiles:
      - "develop"
    container_name: mailculator_processor_develop_app
    image: golang:1.24-alpine
    working_dir: /app
    volumes:
      - mailculator-processor-go-deps:/go
      - ..:/app
    command: tail -f /dev/null
    tty: false
    env_file:
      - develop.env

  db:
    profiles:
      - "develop"
      - "migrations"
    container_name: mailculator_processor_develop_db
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mailculator
      - MYSQL_USER=user
      - MYSQL_USER=pass
    volumes:
      - mailculator-processor-db:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:33060'
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  migrations:
    profiles:
      - "migrations"
    container_name: mailculator_processor_develop_db_migrations
    image: ghcr.io/amacneil/dbmate
    environment:
      - DATABASE_URL=mysql://user:pass@127.0.0.1:3306/mailculator
      - DBMATE_WAIT_TIMEOUT=15s
    restart: no
    volumes:
      - '../db/migrations:/db/migrations'
    network_mode: host
    command: --wait migrate

  locks-storage:
    profiles:
      - "develop"
    container_name: mailculator_processor_develop_locks_storage
    image: valkey/valkey:alpine
    restart: unless-stopped
