networks:
  mailculator-processor-deployments-net:

services:
  app-base: &app-base
    profiles:
      - "none"
    image: golang:1.23-alpine
    working_dir: /app
    environment: &app-base-environment
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
      AWS_REGION: "eu-west-1"
      SMTP_USER: "user"
      SMTP_PASS: "pass"
      SMTP_PORT: "1025"
      SMTP_FROM: "mailer@example.com"
    volumes:
      - ./.cache/go:/go/pkg/mod:cached
      - ..:/app
    networks:
      - mailculator-processor-deployments-net

  test:
    <<: *app-base
    container_name: mailculator_processor_test
    profiles:
      - "test"
    environment:
      <<: *app-base-environment
      AWS_BASE_ENDPOINT: "http://test-aws:4566"
      SMTP_HOST: "test-smtp"
    command: sh -c "go mod tidy && go test ./..."

  local-dev:
    <<: *app-base
    container_name: mailculator_processor_local-dev
    profiles:
      - "local-dev"
    environment:
      <<: *app-base-environment
      AWS_BASE_ENDPOINT: "http://local-dev-aws:4566"
      SMTP_HOST: "local-dev-smtp"
    command: /bin/sh -c "go mod tidy && tail -f /dev/null"
    tty: false

  localstack: &localstack-base
    profiles:
      - "none"
    image: localstack/localstack
    environment:
      DEBUG: 0
      DYNAMODB_SHARE_DB: 1
      DEFAULT_REGION: "eu-west-1"
    volumes:
      - ./resources/localstack:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mailculator-processor-deployments-net

  mailpit: &mailpit-base
    profiles:
      - "none"
    image: axllent/mailpit
    environment:
      MP_SMTP_TLS_CERT: "/certs/cert.pem"
      MP_SMTP_TLS_KEY: "/certs/key.pem"
      MP_SMTP_REQUIRE_STARTTLS: "true"
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
    volumes:
      - ./resources/fake-smtp-certs:/certs
    networks:
      - mailculator-processor-deployments-net

  test-aws:
    <<: *localstack-base
    container_name: mailculator_processor_test_aws
    profiles:
      - "test-deps"
      - "test"

  test-smtp:
    <<: *mailpit-base
    container_name: mailculator_processor_test_smtp
    profiles:
      - "test-deps"
      - "test"

  local-dev-aws:
    <<: *localstack-base
    container_name: mailculator_processor_local-dev_aws
    profiles:
      - "local-dev-deps"
      - "local-dev"
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"

  local-dev-smtp:
    <<: *mailpit-base
    container_name: mailculator_processor_local-dev_smtp
    profiles:
      - "local-dev-deps"
      - "local-dev"
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"

  local-dev-db-admin:
    container_name: mailculator_processor_develop_local-dev_db-admin
    profiles:
      - "local-dev-tools"
      - "local-dev"
    image: aaronshaf/dynamodb-admin
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://local-dev-aws:4566"
      AWS_REGION: "eu-west-1"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
    networks:
      - mailculator-processor-deployments-net
