---
config:
  theme: neo
  layout: dagre
---
flowchart TD
 subgraph App["Multicarrier Email (Daemon)"]
        Pipelines("3x Pipeline Parallele (invio, callback successo e fail)")
        AppCore("Start")
        DataLayer("Data Layer (Outbox Service)")
        SmtpClient("SMTP Client")
  end
 subgraph Storage["Database"]
        MySQL[("MySQL")]
  end
 subgraph External["Servizi Esterni"]
        SMTPServer[("SES")]
  end
    AppCore --> Pipelines
    Pipelines --> DataLayer & SmtpClient
    DataLayer --> MySQL
    SmtpClient --> SMTPServer
