ALTER TABLE emails
    MODIFY COLUMN status ENUM(
        'ACCEPTED','INTAKING','READY','PROCESSING',
        'SENT','FAILED','INVALID',
        'CALLING-SENT-CALLBACK','CALLING-FAILED-CALLBACK','CALLING-INVALID-CALLBACK',
        'SENT-ACKNOWLEDGED','FAILED-ACKNOWLEDGED','INVALID-ACKNOWLEDGED'
    ) NOT NULL;
