name: Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize Go cache directory
        run: mkdir -p ./deployments/.cache/go

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ./deployments/.cache/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: ./deployments/test.sh
