name: Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker-images-cache:
    runs-on: ubuntu-latest
    name: Cache docker images
    strategy:
      matrix:
        include:
          - id: golang
            image: golang:1.23-alpine
          - id: localstack
            image: localstack/localstack
          - id: mailpit
            image: axllent/mailpit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize docker image cache directory
        run: mkdir -p deployments/.cache/docker/${{ matrix.id }}

      - name: Check golang docker image cache
        uses: actions/cache@v4
        id: docker-image-cache
        with:
          path: deployments/.cache/docker/${{ matrix.id }}
          key: ${{ matrix.id }}

      - if: steps.docker-image-cache.outputs.cache-hit != 'true'
        name: Cache docker docker image
        run: |
          docker pull ${{ matrix.image }}
          docker save -o deployments/.cache/docker/${{ matrix.id }}/img.tar ${{ matrix.image }}

      - name: Cache for next job
        uses: actions/cache@v4
        with:
          path: deployments/.cache/docker/${{ matrix.id }}
          key: ${{ matrix.id }}

  go-modules-cache:
    runs-on: ubuntu-latest
    name: Cache golang modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize go cache directory
        run: mkdir -p deployments/.cache/go

      - name: Cache go modules
        uses: actions/cache@v4
        with:
          path: deployments/.cache/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  test:
    runs-on: ubuntu-latest
    name: Tests
    needs: [docker-images-cache, go-modules-cache]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure cache directories
        run: |
          mkdir -p deployments/.cache/go
          mkdir -p deployments/.cache/docker/golang
          mkdir -p deployments/.cache/docker/localstack
          mkdir -p deployments/.cache/docker/mailpit

      - name: Restore golang docker image cache
        uses: actions/cache@v4
        with:
          path: deployments/.cache/docker/golang
          key: golang

      - name: Restore localstack docker image cache
        uses: actions/cache@v4
        with:
          path: deployments/.cache/docker/localstack
          key: localstack

      - name: Restore mailpit docker image cache
        uses: actions/cache@v4
        with:
          path: deployments/.cache/docker/mailpit
          key: mailpit

      - name: Restore go modules cache
        uses: actions/cache@v4
        with:
          path: deployments/.cache/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Loads docker images from cache
        run: |
          docker load -i deployments/.cache/docker/golang/img.tar
          docker load -i deployments/.cache/docker/localstack/img.tar
          docker load -i deployments/.cache/docker/mailpit/img.tar

      - name: Run tests
        run: deployments/test.sh
